version: '3.7'

#################################################
#                                               #
#                     NETWORKS                  #
#                                               #
#################################################
networks:
  baby-monitor-ui:
    driver: bridge

#################################################
#                                               #
#                     SERVICES                  #
#                                               #
#################################################
services:
#################################################
#                         UI                    #
#################################################
  ui:
    container_name: baby-monitor-ui
    image: 192.168.178.35:5000/baby-monitor-ui
    networks:
      - baby-monitor-ui
    ports:
      - "8080:8080"
    restart: unless-stopped
